config/routes.rb
Rails.application.routes.draw do

  root 'home#index'
  get 'home/index'
  get 'home/clear_record'

  devise_for :users, :controllers => { :registrations => 'users'}
  
  get 'plans/index'
  get 'plans/show'

  get 'charges/new'

  resources :charges

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  def new
  end
  def create
    @amount = 500

    customer = Stripe::Customer.create(
      :email => 'example@stripe.com',
      :card => params[:stripeToken]
      )

    charge = Stripe::Charge.create(
      :customer => customer.id,
      :amount => @amount,
      :description => 'Rails Stripe Customer',
      :currency => 'usd'
      )
  rescue Stripe::CardError => e 
    flash[:error] = e.message
    redirect_to charges_path
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  def clear_record

  end
end

app/controllers/plans_controller.rb
class PlansController < ApplicationController
  def index
    @plan = Stripe::Plan.retrieve("basic")
  end

  def show
  end
end

app/controllers/users_controller.rb
class UsersController < Devise::RegistrationsController
  #after_create :set_stripe_customer_id

  def new
    super
  end

  private
  def set_stripe_customer_id
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/charges/create.html.erb
<h2>Thanks, you paid <strong>$5.00</strong>!</h2>

app/views/charges/new.html.erb
<%= form_tag charges_path do %>
  <article>
    <label class="amount">
      <span>Amount: $5.00</span>
    </label>
  </article>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="A month's subscription"
          data-amount="500"></script>
<% end %>

app/views/home/_section1.html.erb
<div class="ui three column grid">
  <div class="column">
  </div>
  <div id="centered" class="column the_sell">    
    <h1 class="super_title">CLEAR YOUR CRIMINAL RECORD</h1>
    <div class='ui small message'>
      <%= link_to '#' do %>
      <p class="sidekick_caption">
        Travel to the USA
      </p>
      <% end %>
      <div class="ui horizontal icon divider">
        <i class="circular legal icon"></i>
      </div>
      <%= link_to '#' do %>
      <p class="sidekick_caption">
        Get Respectable Jobs
      </p>
      <% end %>
    </div>
    <br>
    <%= render 'layouts/signupbutton' %>
  </div>
  <div class="column">
  </div>
</div>

app/views/home/_section2.html.erb
<div class='ui inverted attached message' id="my_section2">

  <div class='header'>How it Works</div>
  <p>Explanation of how it works</p>
</div>
<div class='ui attached message'>
<div class='content'>
content
yada<br>
test
</div>
</div>
<div id="three_clipart_columns" class="ui three column grid">
  <div class="column">
    <div class='ui segment'>
      <%= semantic_icon(:legal) %>
      <p>explanation 1</p>
    </div>
  </div>
  <div class="column">
    <div class='ui segment'>
      <%= semantic_icon(:location) %>
      <p>explanation 1</p>
    </div>
  </div>  
  <div class="column">
    <div class='ui segment'>
      <%= semantic_icon(:mail) %>
      <p>explanation 1</p>
    </div>
  </div>
</div>
<div class='ui segment'>
  test
</div>

app/views/home/_section3.html.erb
<div class='ui message' id="my_section3">
  <div class='header'>Title/Header</div>
  <p>This is section 1</p>
</div>

app/views/home/clear_record.html.erb
clear_record.html.erb

app/views/home/index.html.erb
<div id="pagepiling">
  <div class="section" id="section1">
    <%= render "section1" %>
  </div>
  <div class="section" id="section2">
    <div class="intro">
      <%= render "section2" %>
    </div>
  </div>
  <div class="section" id="section3">
    <div class="intro">
      <%= render "section3" %>
    </div>
  </div>
</div>

<ul id="pagepiling_menu">
  <li data-menuanchor="page1" class="active"><a href="#page1">Page 1</a></li>
  <li data-menuanchor="page2"><a href="#page2">Page 2</a></li>
  <li data-menuanchor="page3"><a href="#page3">Page 3</a></li>
</ul>

app/views/layouts/_header.html.erb
<div id="seethrough" class="ui fixed main menu">
  <div class="container">
    <a class="launch item">
      <%= semantic_icon("list layout") %>
      Dominion Pardons & Waivers
    </a>
    <% if current_user || user_signed_in? %>
    <%= link_to destroy_user_session_path, html_options = {method: :delete } do %>
    <div class="ui right item" id='login'>
      <div class='text'>Logout</div>
    </div>
    <% end %>
    <% else %>
    <%= link_to new_user_session_path do %>
    <div class="ui right item" id='login'>
      <div class='text'>Login</div>
    </div>
    <% end %>
    <% end %>    
    <a href='#' id="testimonials_header" class="right item">
      <%= semantic_icon(:comment) %>
      Testimonials
    </a>
    <a href='#' id="hiw_header" class="right item">
      <%= semantic_icon(:wrench) %>
      How it Works
    </a>
  </div>
</div>
</div>

app/views/layouts/_signupbutton.html.erb
<%= link_to home_clear_record_path do %>
<div id='signupbutton' class='ui huge button'>
  <%= semantic_icon(:key) %>
  Clear Now
</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Striped</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/header' %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/charges.html.erb
<!DOCTYPE html>
<html>
<head>
</head>
<body>
  <%= yield %>
</body>
</html>

app/views/plans/index.html.erb
<h1>Plans#index</h1>
<p>Find me in app/views/plans/index.html.erb</p>
<%= @plan.name %><br>
<%= @plan.amount %>

app/views/plans/show.html.erb
<h1>Plans#show</h1>
<p>Find me in app/views/plans/show.html.erb</p>